# Generated by Django 3.2.22 on 2023-11-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettermod',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletter'},
        ),
    ]
