# Generated by Django 3.2.22 on 2023-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymod',
            name='name',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('memorabilia', 'Memorabilia')], max_length=254, verbose_name='Category Name'),
        ),
    ]
