# Generated by Django 3.2.22 on 2023-10-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=100)),
                ('song_file', models.FileField(blank=True, null=True, upload_to='')),
                ('song_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
