# Generated by Django 3.2.22 on 2023-10-21 14:12

import cloudinary.models
from django.db import migrations
import musicapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmod',
            name='song_file',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, validators=[musicapp.models.validate_mp3_file], verbose_name='raw'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicmod',
            name='song_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
