# Generated by Django 3.2.22 on 2023-11-04 02:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmod',
            name='song_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='song_file'),
        ),
        migrations.AlterField(
            model_name='musicmod',
            name='song_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='song_image'),
        ),
    ]
