# Generated by Django 3.2.22 on 2023-11-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMod',
        ),
    ]
